### PR TITLE
fix: resolve flaky unit tests caused by OVS interface race conditions

### LINKED ISSUE #462: flake: Unit tests — pkg/plugin/plugin_test.go:213
Detected by the QE bot on https://github.com/k8snetworkplumbingwg/ovs-cni/pull/459 (PR #459).

**Check:** `Unit tests`
**Test id:** `pkg/plugin/plugin_test.go:213`
**Reason:** Interface error state unrelated to PR changes which only modify hack/functests.sh script

**Command:** `cd /tmp/qe-pr-459-wt && set -o pipefail; ( make test ) ><local-path> 2>&1; echo "EXIT=$?"; tail -50 <local-path>` (exit 2)

<details><summary>Evidence</summary>

```
if [ ! -f /tmp/qe-pr-459-wt/build/_output/bin//host-local -a `uname` = 'Linux' ]; then\
	cd /tmp/qe-pr-459-wt/build/_output/bin/ && \
	git clone https://github.com/containernetworking/plugins && \
	cd plugins && git checkout v1.0.1 && cd .. && \
	./plugins/build_linux.sh && \
	cp ./plugins/bin/host-local . && \
	rm -rf plugins; \
fi
Cloning into 'plugins'...
Note: switching to 'v1.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 189d0c06 Merge pull request #661 from squeed/firewall-version
Building plugins 
  bandwidth
  firewall
  portmap
  sbr
  tuning
  vrf
  bridge
  host-device
  ipvlan
  loopback
  macvlan
  ptp
  vlan
  dhcp
  host-local
  static
/tmp/qe-pr-459-wt/build/_output/bin//go//bin//go test -mod=readonly ./cmd/... ./pkg/... -v --ginkgo.v
go: downloading github.com/containernetworking/plugins v1.8.0
go: downloading github.com/containernetworking/cni v1.3.0
go: downloading github.com/onsi/ginkgo/v2 v2.28.1
go: downloading github.com/onsi/gomega v1.39.1
go: downloading github.com/vishvananda/netlink v1.3.1
... [12572 lines elided] ...
			}
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=332} "level"=3 "msg"="trying to connect" "database"="Open_vSwitch" "endpoint"="unix:/var/run/openvswitch/db.sock"
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=263} "level"=3 "msg"="successfully connected" "database"="Open_vSwitch" "endpoint"="unix:/var/run/openvswitch/db.sock" "sid"=""
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=332} "level"=3 "msg"="trying to connect" "database"="Open_vSwitch" "endpoint"="unix:/var/run/openvswitch/db.sock"
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=263} "level"=3 "msg"="successfully connected" "database"="Open_vSwitch" "endpoint"="unix:/var/run/openvswitch/db.sock" "sid"=""
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=837} "level"=4 "msg"="transacting operations" "database"="Open_vSwitch" "database"="Open_vSwitch" "operations"="[{Op:select Table:Bridge Row:map[] Rows:[] Columns:[name] Mutations:[] Timeout:<nil> Where:[where column name == test-bridge] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUID: UUIDName:}]"
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=837} "level"=4 "msg"="transacting operations" "database"="Open_vSwitch" "database"="Open_vSwitch" "operations"="[{Op:select Table:Port Row:map[] Rows:[] Columns:[name external_ids] Mutations:[] Timeout:<nil> Where:[where column external_ids includes {map[contIface:eth0 contNetns:/var/run/netns/cnitest-61cf689b-fb4a-b580-681c-be2c7d56e2ba owner:ovs-cni.network.kubevirt.io]}] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUID: UUIDName:}]"
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=837} "level"=4 "msg"="transacting operations" "database"="Open_vSwitch" "database"="Open_vSwitch" "operations"="[{Op:select Table:Port Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[where column name == veth635968de] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUID: UUIDName:}]"
2026/04/10 13:52:42 libovsdb: "caller"={"file"="client.go" "line"=837} "level"=4 "msg"="transacting operations" "database"="Open_vSwitch" "database"="Open_vSwitch" "operations"="[{Op:delete Table:Interface Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[where column name == veth635968de] Until: Durable:<nil> Comment:<nil> Lock:<nil> UUID: UUIDName:} {Op:delete Table:Port Row:map[] Rows:[] Columns:[] Mutations:[] Timeout:<nil> Where:[w
... [truncated]
```

</details>

Close this issue once the underlying flaky test is fixed.

### PR DESCRIPTION
**Pull request by robot-primus**
Closes #462

**What this PR does / why we need it**:
Fixes flaky unit tests caused by two race conditions in OVS interface handling:
1. `validateOvs` (CmdCheck) checked ALL OVS interfaces for errors via `FindInterfacesWithError()`. If any unrelated interface was transiently in error state, the check failed. Now uses a new `InterfaceHasError()` method that checks only the specific host interface being validated.
2. Test `BeforeEach` called `netlink.LinkByName` immediately after `ovs-vsctl add-br`, but the kernel interface may not be available yet. Now uses `Eventually()` with retries to wait for the interface to appear.

**Special notes for your reviewer**:
The same BeforeEach race condition existed in three test files (plugin_test.go, producer_test.go, consumer_test.go) and all three were fixed. The `FindInterfacesWithError()` function is kept unchanged since it is still used by `cleanPorts()` which correctly needs to find all errored interfaces.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by robot-radius — APPROVED** [review]
Code review passed:  Code review approved.

This PR is a clean, well-motivated fix: scoping the error check from all interfaces to the single relevant one in validateOvs is the right architectural move, and the new InterfaceHasError method is well-structured, following the same transact-check-iterate pattern used by FindInterfacesWithError. The Eventually retry in the test BeforeEach blocks is an idiomatic Ginkgo solution to a real race condition. No Clean Code or project-rule violations found. Ready to merge.

## Code review
✅ Approved — no concerns.

<details>
<summary>Recommendations</summary>

- FindInterfacesWithError is now only called from cleanPorts. If cleanPorts could also benefit from per-interface checking in the future, consider whether FindInterfacesWithError still pulls its weight or could be replaced by InterfaceHasError calls to reduce the OVSDB query surface.

</details>

## Analysis

<details>
<summary>Code review</summary>

**Stats**

- Wall time: 42s
- Tokens: 13 in · 2.1k out · 288.2k cache-read · 29.9k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T14-56-36-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Read | 7 | 16s |
| Bash | 10 | 9s |
| Write | 1 | 9s |
| Grep | 1 | 2s |

**Analysis**

**Session overview:** 42s wall time, $0.38 cost, 12 assistant turns, 20 total turns (including tool results). The session followed the prompt's prescribed pipeline cleanly with no loops, retries, or wrong-path recoveries. No narration was emitted between tool calls.

**Wall-time breakdown by segment (LLM round-trip + tool execution):**

| Segment | Duration | Description |
|---------|----------|-------------|
| Prompt → first tool result | ~6s | Initial cache-creation + `cd /tmp/qe-pr-464-wt` |
| 5 parallel per-file diffs | ~5s | Good — followed the per-file diff instruction |
| Read ovsdb.go + 2× git log (parallel) | ~6s | DCO sign-off + context gathering |
| 3× parallel Read (plugin.go, plugin_test.go, consumer_test.go) | ~4s | Full-file context |
| Read ovsdb.go:680-704 | ~2.6s | Partially redundant — lines 700-704 already seen |
| Grep + Read plugin.go:500-530 | ~4s | Caller analysis for FindInterfacesWithError |
| Read ovsdb.go:1-15 | ~1.9s | Returned copyright header, not imports — wasted |
| mkdir -p (unnecessary) | ~2.4s | Output directory already existed |
| Write result JSON | ~9.3s | Dominated by LLM generating the result |

**Irrelevant tokens:** Two git log commands (`--format='%s'` and `--format='%B---COMMIT_END---'`) ran in the same parallel batch; the subject-only variant was subsumed by the full-body variant. No wall-time cost, minor token waste. The Read of `ovsdb.go:1-15` returned only the license header (15 lines of copyright), providing zero review-relevant information. The `mkdir -p` call was unnecessary since the orchestrator creates the output directory before launching the session.

**Concrete suggestions:** No single optimization meets the one-minute wall-time threshold. The three wasted turns (redundant ovsdb.go read, copyright-header read, unnecessary mkdir) together account for ~7s. With the total run at 42s, the session was efficient. No changes recommended.

</details>

<details>
<summary>Script drift</summary>

This project has no `.claude/skills/` directory — no `e2e/SKILL.md`, no `code-quality/SKILL.md`, no referenced skill documents exist. The review prompt's "Go project rules" (5 rules: DCO sign-off, vendored deps, logutils-only logging, goimports ordering, Ginkgo v2 + Gomega dot-imports) are sourced from `AGENTS.md`. All five rules match `AGENTS.md` verbatim in substance.

This PR modifies only Go source and test files (`pkg/ovsdb/ovsdb.go`, `pkg/plugin/plugin.go`, three `*_test.go` files). It does not add a new language, test suite, or top-level area. No skill files are touched.

_No drift detected._

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Code review | $0.3835 | 42s |
| Analysis | $0.8450 | 3m 05s |
| **Total** | **$1.2285** | **3m 47s** |

</details>

**Review by robot-helena — APPROVED** [review]
QA passed:  Review approved, 1 of 4 checks failed (all classified as flakes).

## Quality review
✅ Approved — test coverage looks adequate.

## Test results
❌ 1 of 4 checks failed.

| Check | Status |
|-------|--------|
| Build | ✅ passed |
| Lint | ✅ passed |
| Unit tests | ✅ passed |
| Functest | ❌ failed |

> ⚠️ 1 failure(s) classified as flake(s) and tracked separately:
> - Functest — [https://github.com/k8snetworkplumbingwg/ovs-cni/issues/461](https://github.com/k8snetworkplumbingwg/ovs-cni/issues/461)

**Failures**

<details>
<summary>Functest — 9 Ginkgo test failures: ovs-vsctl add-br/del-br commands failing with exit status 1 in BeforeEach/AfterEach hooks (/tmp/qe-pr-464-wt/tests/node/node.go:63,70, /tmp/qe-pr-464-wt/tests/marker_test.go:33) (exit 2)</summary>

`set -o pipefail; ( make cluster-down 2>/dev/null; make cluster-up && make cluster-sync && E2E_TEST_ARGS="-timeout 30m" make functest; rc=$?; make cluster-down; exit $rc ) >/tmp/qe-logs/functest.log 2>&1; echo "EXIT=$?"; tail -80 /tmp/qe-logs/functest.log`

```
./cluster/down.sh
./cluster/up.sh
+ source ./cluster/cluster.sh
++ export KUBEVIRT_PROVIDER=k8s-1.34
++ KUBEVIRT_PROVIDER=k8s-1.34
++ export KUBEVIRTCI_TAG=2509181951-8264c60a
++ KUBEVIRTCI_TAG=2509181951-8264c60a
++ CLUSTER_PATH=/tmp/qe-pr-464-wt/_kubevirtci/
+ cluster::install
+ '[' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::_get_tag
++ git -C /tmp/qe-pr-464-wt/_kubevirtci/ describe --tags
+ [[ 2509181951-8264c60a != 2509181951-8264c60a ]]
+ '[' '!' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::path
++ echo -n /tmp/qe-pr-464-wt/_kubevirtci/
+ /tmp/qe-pr-464-wt/_kubevirtci//cluster-up/up.sh
selecting podman as container runtime
Download the image quay.io/kubevirtci/k8s-1.34:2509181951-8264c60a
time="2026-04-10T15:07:02Z" level=info msg="Using local image quay.io/kubevirtci/k8s-1.34:2509181951-8264c60a"
time="2026-04-10T15:07:02Z" level=info msg="Using local image quay.io/libpod/registry:2.8.2"
time="2026-04-10T15:07:03Z" level=info msg="waiting for node to come up"
VM is up
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==' | sudo tee /root/.ssh/authorized_keys > /dev/null"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: sudo service sshd restart"
Redirecting to /bin/systemctl restart sshd.service
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: lspci -D -d 8086:2668"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: readlink /sys/bus/pci/devices/0000:00:04.0/driver | awk -F'/' '{print $NF}'"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: modprobe -i vfio-pci"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: if [[ ! -d /sys/bus/pci/devices/0000:00:04.0 ]]; then echo 'PCI address does not exist!' && exit 1; fi"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: if [[ ! -d /sys/bus/pci/devices/0000:00:04.0/iommu/ ]]; then echo 'No vIOMMU found in the VM' && exit 1; fi"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: [[ 'snd_hda_intel' != 'vfio-pci' ]] && echo 0000:00:04.0 > /sys/bus/pci/devices/0000:00:04.0/driver/unbind && echo 'vfio-pci' > /sys/bus/pci/devices/0000:00:04.0/driver_override && echo 0000:00:04.0 > /sys/bus/pci/drivers/vfio-pci/bind"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: lspci -D -d 8086:2415"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: readlink /sys/bus/pci/devices/0000:00:05.0/driver | awk -F'/' '{print $NF}'"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: modprobe -i vfio-pci"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: if [[ ! -d /sys/bus/pci/devices/0000:00:05.0 ]]; then echo 'PCI address does not exist!' && exit 1; fi"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: if [[ ! -d /sys/bus/pci/devices/0000:00:05.0/iommu/ ]]; then echo 'No vIOMMU found in the VM' && exit 1; fi"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: [[ 'snd_intel8x0' != 'vfio-pci' ]] && echo 0000:00:05.0 > /sys/bus/pci/devices/0000:00:05.0/driver/unbind && echo 'vfio-pci' > /sys/bus/pci/devices/0000:00:05.0/driver_override && echo 0000:00:05.0 > /sys/bus/pci/drivers/vfio-pci/bind"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: if [ -f /home/vagrant/enable_audit ]; then echo 'apiVersion: audit.k8s.io/v1\nkind: Policy\nrules:\n- level: Metadata' | tee /etc/kubernetes/audit/adv-audit.yaml > /dev/null; fi"
time="2026-04-10T15:07:18Z" level=info msg="[node 1]: timeout=30; interval=5; while ! hostnamectl | grep Transient; do echo \"Waiting for dhclient to set the hostname from dnsmasq\"; sleep $interval; timeout=$((timeout - interval)); [ $timeout -le 0 ] && exit 1; done"
Transient hostname: node01
time="2026-04-10T15:07:19Z" level=info msg="[node 1]: swapoff -a"
time="2026-04-10T15:07:19Z" level=info msg="[node 1]: until ip address show dev eth0 | grep global | grep inet6; do sleep 1; done"
    inet6 fd00::101/128 scope global tentative noprefixroute 
time="2026-04-10T15:07:19Z" level=info msg="[node 1]: timeout=60; interval=5; while ! systemctl status crio | grep -w \"active\"; do echo \"Waiting for cri-o service to be ready\"; sleep $interval; timeout=$((timeout - interval)); if [[ $timeout -le 0 ]]; then exit 1; fi; done"
     Active: active (running) since Fri 2026-04-10 15:07:17 UTC; 1s ago

... [491 lines elided] ...

  [38;5;9m[FAIL][0m [0movs-mirror 0.3.0 [38;5;243movs traffic mirroring tests [38;5;9m[1mwhen an OVS bridge is configured on a node [BeforeEach] [38;5;243mand both consumer and producer network attachment definitions are defined with a mirror configuration [0mand 3 pods (2 producers and 1 consumer) are connected through it [38;5;243mconsumer pod should be able to monitor network traffic between producer pods[0m
  [38;5;243m/tmp/qe-pr-464-wt/tests/node/node.go:70[0m
  [38;5;9m[FAIL][0m [0movs-cni 1.0.0 [38;5;243mpod ovs-bridge connectivity tests [38;5;9m[1mwhen an OVS bridge is configured on a node [BeforeEach] [38;5;243mand a network attachment definition is defined [0mand two pods are connected through it [38;5;243mthey should be able to communicate over the network[0m
  [38;5;243m/tmp/qe-pr-464-wt/tests/node/node.go:70[0m
  [38;5;9m[FAIL][0m [0movs-mirror 0.4.0 [38;5;243movs traffic mirroring tests [38;5;9m[1mwhen an OVS bridge is configured on a node [BeforeEach] [38;5;243mand both consumer and producer network attachment definitions are defined with a mirror configuration [0mand 3 pods (2 producers and 1 consumer) are connected through it [38;5;243mconsumer pod should be able to monitor network traffic between producer pods[0m
  [38;5;243m/tmp/qe-pr-464-wt/tests/node/node.go:70[0m
  [38;5;9m[FAIL][0m [0movs-mirror 0.3.1 [38;5;243movs traffic mirroring tests [38;5;9m[1mwhen an OVS bridge is configured on a node [BeforeEach] [38;5;243mand both consumer and producer network attachment definitions are defined with a mirror configuration [0mand 3 pods (2 producers and 1 consumer) are connected through it [38;5;243mconsumer pod should be able to monitor network traffic between producer pods[0m
  [38;5;243m/tmp/qe-pr-464-wt/tests/node/node.go:70[0m
  [38;5;9m[FAIL][0m [0movs-cni 0.3.0 [38;5;243mpod ovs-bridge connectivity tests [38;5;9m[1mwhen an OVS bridge is configured on a node [BeforeEach] [38;5;243mand a network attachment definition is defined [0mand two pods are connected through it [38;5;243mthey should be able to communicate over the network[0m
  [38;5;243m/tmp/qe-pr-464-wt/tests/node/node.go:70[0m
  [38;5;9m[FAIL][0m [0movs-cni-marker [38;5;243mbridge resource reporting [38;5;9m[1m[It] should be reported only when available on node[0m
  [38;5;243m/tmp/qe-pr-464-wt/tests/marker_test.go:33[0m

[38;5;9m[1mRan 14 of 14 Specs in 311.261 seconds[0m
[38;5;9m[1mFAIL![0m -- [38;5;10m[1m5 Passed[0m | [38;5;9m[1m9 Failed[0m | [38;5;11m[1m0 Pending[0m | [38;5;14m[1m0 Skipped[0m
[38;5;228mYou're using deprecated Ginkgo functionality:[0m
[38;5;228m=============================================[0m
  [38;5;11mSupport for custom reporters has been removed in V2.  Please read the documentation linked to below for Ginkgo's new behavior and for a migration path:[0m
  [1mLearn more at:[0m [38;5;14m[4mhttps://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-custom-reporters[0m

[38;5;243mTo silence deprecations that can be silenced set the following environment variable:[0m
  [38;5;243mACK_GINKGO_DEPRECATIONS=2.28.1[0m

--- FAIL: TestPlugin (311.26s)
FAIL
FAIL	github.com/k8snetworkplumbingwg/ovs-cni/tests	311.288s
FAIL
make: *** [Makefile:80: functest] Error 1
./cluster/down.sh
+++ realpath ./cluster/down.sh
++ dirname /tmp/qe-pr-464-wt/cluster/down.sh
+ SCRIPTS_PATH=/tmp/qe-pr-464-wt/cluster
+ source /tmp/qe-pr-464-wt/cluster/cluster.sh
++ export KUBEVIRT_PROVIDER=k8s-1.34
++ KUBEVIRT_PROVIDER=k8s-1.34
++ export KUBEVIRTCI_TAG=2509181951-8264c60a
++ KUBEVIRTCI_TAG=2509181951-8264c60a
++ CLUSTER_PATH=/tmp/qe-pr-464-wt/_kubevirtci/
+ cluster::install
+ '[' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::_get_tag
++ git -C /tmp/qe-pr-464-wt/_kubevirtci/ describe --tags
+ [[ 2509181951-8264c60a != 2509181951-8264c60a ]]
+ '[' '!' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::path
++ echo -n /tmp/qe-pr-464-wt/_kubevirtci/
+ /tmp/qe-pr-464-wt/_kubevirtci//cluster-up/down.sh
selecting podman as container runtime
```
_(output trimmed: middle elided)_
</details>

## Analysis

<details>
<summary>Quality review</summary>

**Stats**

- Wall time: 44s
- Tokens: 59 in · 1.8k out · 95.3k cache-read · 25.5k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T15-02-38-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Write | 1 | 17s |
| Read | 2 | 5s |
| Bash | 3 | 5s |

**Analysis**

The review session ran efficiently in 44 seconds. Tool call breakdown: git diff took 5 seconds (empty result), two Read calls on ovsdb.go each took 5 seconds, and generating the final result took 17 seconds. The two Read calls showed minor overlap—lines 740-759 followed by 720-754—reading 20 lines twice, but this is negligible.

No loops, retries, or wrong paths occurred. The session correctly identified that HEAD matched the reviewed commit and checked the inline comment location. The 17-second result generation time is normal for a well-reasoned approval decision.

**Concrete suggestions:** None. The session took 44 seconds total; no individual inefficiency saved more than one minute of wall time. The overlapping Read calls wasted perhaps 2 seconds—well below the noise floor.

</details>

<details>
<summary>Test run</summary>

**Stats**

- Wall time: 13m 51s
- Tokens: 70 in · 6.4k out · 144.6k cache-read · 74.4k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T15-02-38-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 5 | 12m 09s |
| Write | 1 | 1m 25s |
| Read | 1 | 5s |

</details>

<details>
<summary>Script drift</summary>

_No drift detected._

The Makefile defines four test targets (build, lint, test, functest), and the test prompt runs all four. The `make test` target covers `./cmd/... ./pkg/...`, which includes all unit test files modified by this PR (pkg/mirror-consumer/consumer_test.go, pkg/mirror-producer/producer_test.go, pkg/plugin/plugin_test.go). The `make functest` target covers the tests/ directory via `${GO} test -v ./tests`. No new packages or test suites were added by PR #464.

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Quality review | $0.1512 | 44s |
| Test run | $0.4191 | 13m 51s |
| Analysis | $0.4993 | 2m 31s |
| **Total** | **$1.0696** | **17m 06s** |

</details>

File: pkg/plugin/plugin.go [hunk 1]
```diff
@@ -862,12 +862,12 @@ func validateOvs(args *skel.CmdArgs, netconf *types.NetConf, hostIfname string)
 		return fmt.Errorf("Error: bridge %s is not found in OVS", netconf.BrName)
 	}
 
-	ifaces, err := ovsBridgeDriver.FindInterfacesWithError()
+	hasError, err := ovsBridgeDriver.InterfaceHasError(hostIfname)
```
Comment (phoracek) [inline pkg/plugin/plugin.go:865]: Please add a test which will cover the case where this has an error

**Review by robot-radius — APPROVED** [review]
Code review passed:  Code review approved with 1 nit.

The PR makes two focused, well-motivated changes: narrowing the interface error check in validateOvs to the specific interface under validation (eliminating false failures from unrelated interfaces), and adding Eventually-based retry logic in three test files to handle the OVS-to-kernel race on bridge creation — both are clean, well-named, and clearly commented. The one observation is that InterfaceHasError duplicates transaction boilerplate already handled by the findByCondition helper, as an earlier reviewer also noted. Ready to merge.

## Code review
✅ Approved — 1 nit(s).

<details>
<summary>Nits</summary>

- `pkg/ovsdb/ovsdb.go:725` — InterfaceHasError duplicates the select/transact/error-check boilerplate that findByCondition already encapsulates. Reusing findByCondition with an errors.Is(err, errObjectNotFound) guard (as the prior reviewer suggested) would eliminate ~12 lines of duplication and keep the codebase consistent. The Columns list also fetches "name" which is never read — only "error" is needed.

</details>

## Analysis

<details>
<summary>Code review</summary>

**Stats**

- Wall time: 1m 56s
- Tokens: 1.2k in · 4.9k out · 297.4k cache-read · 33.4k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T15-24-00-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Read | 7 | 52s |
| Bash | 10 | 50s |
| Write | 1 | 8s |
| Grep | 2 | 0s |

**Analysis**

**Wall time breakdown (total ~116 s, 25 LLM turns, 20 tool calls):**

| Segment | Wall time | Activity |
|---|---|---|
| Lines 28-33 | ~35 s | 2 927-char thinking block + 4 parallel reads (Grep `FindInterfacesWithError`, Read 3 test files). Tool I/O was trivial; almost all time was LLM inference. |
| Lines 42-44 | ~34 s | 2 588-char thinking block (final verdict synthesis) + trivial `mkdir`. Again, nearly pure inference time. |
| Lines 38-41 | ~8 s | Two sequential Reads of `plugin.go` at offsets 505 and 855. |
| Remaining 17 turns | ~39 s | Diffs, DCO check, grep, result write. |

These two thinking blocks account for **~60 %** of wall time.

**Redundant or low-value work:**

- **Three separate accesses to `ovsdb.go`:** Read at offset 680 (line 18), Grep for `findByCondition` (line 23), Read at offset 780 (line 26). A single Read with a wider range (e.g., offset 680, limit 140) would have covered both regions and the grep target in one call, saving one LLM round-trip.
- **Two sequential Reads of `plugin.go`** (lines 38, 40) at offsets 505 and 855, each followed by its own LLM turn. One Read with limit ~380 would have covered both regions in a single turn, saving ~4 s.
- **Test-file Reads (lines 30-32):** The reviewer re-read three `_test.go` files to verify import ordering, but the per-file diffs (lines 15-17) already contained the full import blocks. These Reads were redundant — the information was already in context.

**Loops/retries/wrong paths:** None observed. The session followed the prompt pipeline linearly with no retries or error recovery.

**Suggestions:**

1. **Instruct wider Reads.** Add to the prompt: "When you need context around a diff hunk, read a generous range (200+ lines) in one call rather than making multiple narrow Reads of the same file." This would have collapsed 5 Read calls into 2, eliminating ~2 LLM round-trips and saving roughly **1-2 minutes** of inference time.

2. **Prohibit re-reading files whose diffs are already in context.** Add: "Do not Read a file solely to verify information already visible in the per-file diff (e.g., import blocks, function signatures). Use the diff you already have." This would have eliminated the 3 test-file Reads and saved one full round-trip (~35 s of the line 28-33 segment is partly attributable to processing those results).

</details>

<details>
<summary>Script drift</summary>

The project has **no** `.claude/skills/` directory. The prompt's "Project-specific rules" are sourced from `AGENTS.md`, not from skill files. Since the files referenced in the task (`.claude/skills/e2e/SKILL.md`, `.claude/skills/code-quality/SKILL.md`) do not exist, the skill-vs-prompt comparison is not applicable.

**AGENTS.md vs. prompt rule comparison:**

All five inlined Go rules and the DCO rule match `AGENTS.md` exactly. One discrepancy:

- **AGENTS.md** states "Linting: 20+ linters enabled. Relaxed rules in `_test.go` files. Run `make lint` before submitting." The prompt does not inline this as a review rule, but the prompt also says "Do NOT run builds, tests, or linters," so the omission is intentional and not contradictory.

This PR modified only `pkg/` source files — no changes to `AGENTS.md`, skill files, or test infrastructure. No new languages, test suites, or top-level areas were introduced.

_No drift detected._

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Code review | $0.4843 | 1m 56s |
| Analysis | $0.8050 | 3m 02s |
| **Total** | **$1.2893** | **4m 58s** |

</details>

**Review by phoracek — CHANGES_REQUESTED** [review]

File: pkg/ovsdb/ovsdb.go [hunk 2]
```diff
@@ -721,6 +721,35 @@ func (ovsd *OvsDriver) FindInterfacesWithError() ([]string, error) {
 	return names, nil
 }
 
+// InterfaceHasError checks whether a specific interface is in error state
+func (ovsd *OvsDriver) InterfaceHasError(ifaceName string) (bool, error) {
```
Comment (robot-helena) [inline pkg/ovsdb/ovsdb.go:725]: New public method InterfaceHasError lacks unit tests

File: pkg/plugin/plugin.go (hunk 1 above)
Comment (robot-helena) [inline pkg/plugin/plugin.go:865]: Modified error-checking behavior lacks test coverage for the error case (interface in error state)

**Review by robot-helena — CHANGES_REQUESTED** [review]
QA failed:  Review requested 2 changes, 1 of 4 checks failed (all classified as flakes).

## Quality review
❌ Requested changes — 2 concern(s).

<details>
<summary>Concerns</summary>

This PR adds a new public method `InterfaceHasError` in pkg/ovsdb/ovsdb.go and modifies the error-checking logic in pkg/plugin/plugin.go to use this new method. However, the PR lacks test coverage for both the new method and the modified behavior. Specifically: (1) The new `InterfaceHasError` method has no unit tests, and (2) as noted in a prior review comment, the error path in validateOvs where an interface is in error state is not tested.

- `pkg/ovsdb/ovsdb.go:725` — New public method InterfaceHasError lacks unit tests
- `pkg/plugin/plugin.go:865` — Modified error-checking behavior lacks test coverage for the error case (interface in error state)

</details>

## Test results
❌ 1 of 4 checks failed.

| Check | Status |
|-------|--------|
| Build | ✅ passed |
| Lint | ✅ passed |
| Unit tests | ✅ passed |
| Functest | ❌ failed |

> ⚠️ 1 failure(s) classified as flake(s) and tracked separately:
> - Functest — [https://github.com/k8snetworkplumbingwg/ovs-cni/issues/461](https://github.com/k8snetworkplumbingwg/ovs-cni/issues/461)

**Failures**

<details>
<summary>Functest — Cluster-up failed: dnsmasq container could not bind to port 8443 (already in use) (exit 2)</summary>

`make cluster-down 2>/dev/null; make cluster-up && make cluster-sync && E2E_TEST_ARGS="-timeout 30m" make functest; rc=$?; make cluster-down; exit $rc`

```
./cluster/down.sh
./cluster/up.sh
+ source ./cluster/cluster.sh
++ export KUBEVIRT_PROVIDER=k8s-1.34
++ KUBEVIRT_PROVIDER=k8s-1.34
++ export KUBEVIRTCI_TAG=2509181951-8264c60a
++ KUBEVIRTCI_TAG=2509181951-8264c60a
++ CLUSTER_PATH=/tmp/qe-pr-464-wt/_kubevirtci/
+ cluster::install
+ '[' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::_get_tag
++ git -C /tmp/qe-pr-464-wt/_kubevirtci/ describe --tags
+ [[ 2509181951-8264c60a != 2509181951-8264c60a ]]
+ '[' '!' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::path
++ echo -n /tmp/qe-pr-464-wt/_kubevirtci/
+ /tmp/qe-pr-464-wt/_kubevirtci//cluster-up/up.sh
selecting podman as container runtime
Download the image quay.io/kubevirtci/k8s-1.34:2509181951-8264c60a
time="2026-04-10T15:33:19Z" level=info msg="Using local image quay.io/kubevirtci/k8s-1.34:2509181951-8264c60a"
Failed to start dnsmasq container: Error response from daemon: cannot listen on the TCP port: listen tcp4 127.0.0.1:8443: bind: address already in use
Retry creating and starting dnsmasq container
Failed to start dnsmasq container: Error response from daemon: cannot listen on the TCP port: listen tcp4 127.0.0.1:8443: bind: address already in use
Retry creating and starting dnsmasq container
Failed to start dnsmasq container: Error response from daemon: cannot listen on the TCP port: listen tcp4 127.0.0.1:8443: bind: address already in use
Retry creating and starting dnsmasq container
dnsmasq container failed to start 3 timesfailed to found the container with name k8s-1.34-dnsmasq
make: *** [Makefile:98: cluster-up] Error 1
./cluster/down.sh
+++ realpath ./cluster/down.sh
++ dirname /tmp/qe-pr-464-wt/cluster/down.sh
+ SCRIPTS_PATH=/tmp/qe-pr-464-wt/cluster
+ source /tmp/qe-pr-464-wt/cluster/cluster.sh
++ export KUBEVIRT_PROVIDER=k8s-1.34
++ KUBEVIRT_PROVIDER=k8s-1.34
++ export KUBEVIRTCI_TAG=2509181951-8264c60a
++ KUBEVIRTCI_TAG=2509181951-8264c60a
++ CLUSTER_PATH=/tmp/qe-pr-464-wt/_kubevirtci/
+ cluster::install
+ '[' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::_get_tag
++ git -C /tmp/qe-pr-464-wt/_kubevirtci/ describe --tags
+ [[ 2509181951-8264c60a != 2509181951-8264c60a ]]
+ '[' '!' -d /tmp/qe-pr-464-wt/_kubevirtci/ ']'
++ cluster::path
++ echo -n /tmp/qe-pr-464-wt/_kubevirtci/
+ /tmp/qe-pr-464-wt/_kubevirtci//cluster-up/down.sh
selecting podman as container runtime

```
</details>

## Analysis

<details>
<summary>Quality review</summary>

**Stats**

- Wall time: 1m 34s
- Tokens: 658 in · 4.5k out · 357.1k cache-read · 43.5k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T15-30-29-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 9 | 29s |
| Read | 5 | 27s |
| Write | 1 | 13s |
| Grep | 4 | 10s |
| Glob | 1 | 0s |

**Analysis**

The review stage executed 20 tool calls (9 Bash, 5 Read, 4 Grep, 1 Glob, 1 Write) with minimal assistant output (3 words) and 12 thinking blocks (~1200 words).

Wall time instrumentation appears broken—all tool calls report 0ms, making it impossible to identify concrete performance bottlenecks with wall-time data.

Based on call patterns:

**Potential inefficiency**: The review made 9 Bash calls including 4 separate `git diff origin/main...HEAD -- <file>` commands for individual files, followed by 4 grep passes over those diffs. This could be consolidated: fetch the full diff once with `git diff origin/main...HEAD`, then parse in-memory to extract per-file changes and search for patterns. However, without timing data, the actual time savings is unknown and likely well under one minute given the small changeset (5 files).

**File re-reads**: plugin.go was Read 3 times, but using targeted line ranges (850-880, 780-800, 865-868) totaling 53 lines from a 920-line file. This is efficient compared to reading the full file once.

**Suggestion**: Fix the wall-time instrumentation in the stream-json logger. Without accurate timing data, performance analysis is guesswork.

</details>

<details>
<summary>Test run</summary>

**Stats**

- Wall time: 1m 50s
- Tokens: 70 in · 3.1k out · 135.6k cache-read · 14.1k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T15-30-29-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 5 | 1m 07s |
| Write | 1 | 22s |
| Read | 1 | 7s |

</details>

<details>
<summary>Script drift</summary>

_No drift detected._

Verification:
1. **Makefile test targets** (`test`, `test-%`, `functest`) are all invoked by the test prompt via `make build`, `make lint`, `make test`, and the functest cluster sequence.
2. **PR 464** modified only existing packages (pkg/ovsdb, pkg/plugin, pkg/mirror-consumer, pkg/mirror-producer) and their tests—no new packages added.
3. **Makefile and .golangci.yml** unchanged in this PR.

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Quality review | $0.3403 | 1m 34s |
| Test run | $0.1398 | 1m 50s |
| Analysis | $0.4194 | 3m 00s |
| **Total** | **$0.8995** | **6m 25s** |

</details>

File: pkg/ovsdb/ovsdb.go [hunk 3]
```diff
@@ -721,6 +721,35 @@ func (ovsd *OvsDriver) FindInterfacesWithError() ([]string, error) {
...
+		return false, errors.New(operationResult.Error)
+	}
+
+	for _, row := range operationResult.Rows {
+		if hasError(row) {
+			return true, nil
+		}
+	}
+	return false, nil
+}
```
[the remark this answers is not in the document]
Comment (robot-primus) [reply pkg/ovsdb/ovsdb.go:735]: Done in 2a73eae7 -- refactored InterfaceHasError to use findByCondition, handling errObjectNotFound for the missing-interface case.

File: pkg/plugin/plugin.go (hunk 1 above)
Comment (robot-primus) [reply pkg/plugin/plugin.go:865]: Done in 2a73eae7 -- added a "validate interface error state" test context in plugin_test.go that deletes the host veth, waits for the OVS error, then calls validateOvs directly and asserts it returns an error containing "error state".

File: pkg/ovsdb/ovsdb.go (hunk 2 above)
Comment (robot-primus) [reply pkg/ovsdb/ovsdb.go:725]: Done in 2a73eae7 -- added pkg/ovsdb/ovsdb_test.go with unit tests for the hasError helper (empty string, non-empty error string, missing key, non-string value). InterfaceHasError itself is also exercised via the new integration test in plugin_test.go.

File: pkg/plugin/plugin.go (hunk 1 above)
Comment (robot-primus) [reply pkg/plugin/plugin.go:865]: Done in 2a73eae7 -- the new "validate interface error state" test in plugin_test.go covers the error case by breaking the host interface and asserting validateOvs returns an error about the interface being in error state.

**Comment by robot-primus** [comment]
Address review passed:  addressed 4 threads.

Refactored InterfaceHasError to use the existing findByCondition helper, reducing code duplication. Added unit tests for the hasError helper in pkg/ovsdb/ovsdb_test.go and an integration test in pkg/plugin/plugin_test.go that verifies validateOvs detects interfaces in error state by deleting a host veth and calling validateOvs directly. All changes verified: make build, make lint, make test, and functional tests (14/14 passed) all exit 0.

## Address review
✅ Addressed 4 threads.

<details>
<summary>✅ Addressed (4)</summary>

- `PRRT_kwDOCKJfZs56Kmab` — Done in 2a73eae7 -- refactored InterfaceHasError to use findByCondition, handling errObjectNotFound for the missing-interface case.  (2a73eae7)
- `PRRT_kwDOCKJfZs56LBuH` — Done in 2a73eae7 -- added a "validate interface error state" test context in plugin_test.go that deletes the host veth, waits for the OVS error, then calls validateOvs directly and asserts it returns an error containing "error state".  (2a73eae7)
- `PRRT_kwDOCKJfZs56LKQh` — Done in 2a73eae7 -- added pkg/ovsdb/ovsdb_test.go with unit tests for the hasError helper (empty string, non-empty error string, missing key, non-string value). InterfaceHasError itself is also exercised via the new integration test in plugin_test.go.  (2a73eae7)
- `PRRT_kwDOCKJfZs56LKQo` — Done in 2a73eae7 -- the new "validate interface error state" test in plugin_test.go covers the error case by breaking the host interface and asserting validateOvs returns an error about the interface being in error state.  (2a73eae7)

</details>

<details>
<summary>🛑 Pushback (0)</summary>

_(none)_

</details>

<details>
<summary>⏭ Deferred (0)</summary>

_(none)_

</details>

## Analysis

<details>
<summary>Fix run</summary>

**Stats**

- Wall time: 23m 15s
- Tokens: 77 in · 19.3k out · 3133.2k cache-read · 93.5k cache-create
- Run dir: `/tmp/qe-runs/2026-04-10T23-45-58-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 21 | 17m 42s |
| Read | 5 | 2m 05s |
| ToolSearch | 1 | 1m 37s |
| TodoWrite | 7 | 46s |
| Write | 3 | 24s |
| Edit | 2 | 18s |
| Grep | 3 | 11s |
| Glob | 3 | 7s |
| Skill | 1 | 0s |

**Analysis**

## Fix run analysis

### Session overview

Total wall time: **23.1 minutes**. The session addressed all 4 review threads, produced a single commit (`2a73eae7`), and passed all verification gates (build, lint, unit tests, 14/14 functional tests). No retries or wrong-path recoveries were needed.

### Wall-time breakdown by phase

| Phase | Duration | Notes |
|---|---|---|
| Exploration + thinking | 3.9 min | Skill load, code reads, two thinking blocks |
| Implementation | 1.1 min | Edits, file writes, commit |
| Build + lint + unit test | 1.2 min | All passed first try |
| Functest polling | 16.4 min | 8 polls at ~2 min each |
| Result writing | 0.6 min | SHA lookup + JSON write |

The functest polling (71% of wall time) follows the prescribed polling pattern and is inherent to the cluster lifecycle. No optimization is available within the agent.

### Irrelevant or wasted tokens

1. **Duplicate thinking blocks.** The agent produced two large thinking blocks — 9,252 chars (line 22) and 6,659 chars (line 33) — analyzing the *same four threads identically*. The second block starts with "Now I have a clear picture. Let me analyze each thread:" and rehashes the first. The gap between lines 32–35 was **97 seconds**, entirely spent re-deriving the same plan. This is the single largest non-polling waste.

2. **ToolSearch for TodoWrite** (line 34). The agent fetched the deferred schema for `TodoWrite` between the two thinking blocks, adding latency. TodoWrite was then called **7 times** throughout the session, each call repeating the full todo-list state for only 4 items. For a linear 4-thread fix with no branching, task tracking added overhead without value.

3. **Duplicate Read of `plugin_test.go`** (lines 18 and 49). The file was read once during exploration and again before editing. The second read was unnecessary — the agent had just written a new test file and only needed to confirm insertion point context it already had.

4. **Narration between tool calls** (6 text messages, 569 chars). The prompt explicitly forbids assistant text between tool calls. Messages like "All tests pass. Let me verify the new test ran specifically." violate this rule. The token cost is small but it signals the agent wasn't fully following the communication discipline.

### Loops and retries

None. Build, lint, and tests all passed on the first run. The 8 functest polls are not retries — they are the mandated polling pattern. The session was straight-line: read → think → implement → verify → write result.

### Receiving-review skill compliance

The agent invoked `superpowers:receiving-code-review` immediately (line 3). All 4 input threads appear in the result file with action `addressed`. No threads were dropped, silently ignored, or given pushback/deferred without justification. Compliance is correct.

### GitHub comment posting

No `gh api`, `gh pr comment`, `gh pr review`, or GraphQL mutation calls were found. The agent correctly left all GitHub side-effects to the orchestrator.

### Suggestions for improvement

1. **Eliminate the redundant second thinking block** (~1.5 min saved). The agent should commit to its plan after the first analysis pass rather than pausing to fetch `TodoWrite`, then re-analyzing all threads from scratch. Instructing the agent to produce its per-thread action plan in a single thinking block and proceed directly to edits would cut the exploration phase by roughly 40%.

2. **Skip TodoWrite for small, linear fix sessions** (~1 min saved across 7 calls + associated LLM turns). When the thread count is ≤ 5 and there are no failing checks, task tracking adds latency without aiding coordination. The prompt could instruct the agent to skip TodoWrite when the fix set is trivially small, or the skill could be pre-loaded to avoid the ToolSearch detour.

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Fix run | $2.6328 | 23m 15s |
| Analysis | $0.5717 | 2m 10s |
| **Total** | **$3.2045** | **25m 24s** |

</details>

**Review by robot-radius — APPROVED** [review]
Code review passed:  Code review approved.

This is a well-structured refactoring that replaces a broad FindInterfacesWithError scan with a focused InterfaceHasError check, correctly leveraging the existing findByCondition helper to eliminate duplication and narrow the blast radius of the validation. The new InterfaceHasError method is clean, short, and follows the same pattern as every other findByCondition consumer in the file. The import ordering in new files follows goimports conventions, the test files correctly use Ginkgo v2 and Gomega dot-imports, and both commits carry proper DCO sign-offs. All four prior review threads have been addressed in the current code: the refactoring to use findByCondition is applied, the unit tests for hasError are present, and the integration test for the error-state path has been added. No Clean Code violations found. Ready to merge.

## Code review
✅ Approved — no concerns.

<details>
<summary>Recommendations</summary>

- Consider whether FindInterfacesWithError (now unused by the plugin) should be deprecated or removed in a follow-up to avoid dead-code accumulation, since its only consumer was the validateOvs call that this PR replaces.

</details>

## Analysis

<details>
<summary>Code review</summary>

**Stats**

- Wall time: 57s
- Tokens: 835 in · 2.7k out · 342.3k cache-read · 33.9k cache-create
- Run dir: `/tmp/qe-runs/2026-04-11T00-11-54-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 12 | 21s |
| Read | 7 | 17s |
| Write | 1 | 11s |
| Grep | 4 | 3s |

**Analysis**

**Run summary**: 57s wall time, 25 turns, $0.46 cost. The session correctly followed the per-file diff strategy and parallelized the 7 `git diff` calls (all returned within ~45ms of each other at 00:12:12). No narrative text was emitted between tool calls — good compliance with communication discipline.

**Costliest turns by wall time:**

| Gap | Lines | What happened | Seconds |
|-----|-------|---------------|---------|
| Result composition | 48→50 | Model composed the final review JSON and wrote it | 10.7s |
| 7 parallel diffs | 6→14 | 7 per-file `git diff` Bash calls dispatched in parallel | 8.6s |
| Review phase 3 | 34→38 | Read 2 files + Grep for `findByCondition` | 4.9s |
| Review phase 2 | 30→33 | Read `plugin_test.go` (duplicate) + Grep | 4.3s |
| Thread verification | 24→28 | 3 parallel Read calls for thread check | 4.1s |

**Duplicate file reads:**
- `pkg/ovsdb/ovsdb.go` read at lines 25 and 41 — the second read was to check imports, but the file was already fully in context.
- `pkg/plugin/plugin_test.go` read at lines 27 and 31 — re-read 4 turns later to verify thread resolution, but the content hadn't changed.

These 2 duplicate reads cost ~2 turns of API latency (~4-5s combined).

**Sequential git log calls (lines 21, 23):** The session first ran `git log --format='%H %s'` (subjects only), then immediately followed with `git log --format='%B---END---'` (full bodies) to check DCO trailers. A single call with `--format='%B---END---'` would have sufficed, saving one round-trip (~3s).

**Double grep for imports (lines 42, 45):** First grepped for `import`, then refined to `^import`. One targeted grep would have sufficed (~3s saved).

**Unnecessary mkdir (line 47):** Ran `mkdir -p` on the output directory that the orchestrator had already created. Harmless but adds a turn (~3s).

**Concrete suggestions:**

1. **Instruct the prompt to use `git log --format='%B---END---'` from the start** instead of a two-step log inspection. This eliminates one sequential round-trip (~3s). The prompt already specifies per-file diffs to avoid pagination; it should do the same for commit body inspection.

2. **Add a prompt instruction: "Do not re-read a file you have already read in full in this session."** The two duplicate reads of `ovsdb.go` and `plugin_test.go` added ~4-5s of wasted latency and ~10k tokens of redundant context. A single sentence in the review pipeline section would prevent this.

</details>

<details>
<summary>Script drift</summary>

The code-review prompt inlines five Go project rules (DCO sign-off, vendored deps, logutils.Log logging, goimports ordering, Ginkgo v2 + Gomega). There is no `.claude/skills/` directory in this repository — the project uses `AGENTS.md` as its sole source of agent-facing conventions.

**Cross-reference of inlined rules against AGENTS.md:**

| Prompt rule | AGENTS.md equivalent | Status |
|---|---|---|
| DCO `Signed-off-by` trailer | "Always sign off commits with `git commit -s`" | Match |
| Vendor must match go.mod/go.sum | "Dependencies are vendored… run `make dep`" | Match |
| `logutils.Log` only, Logrus banned | "Logging: Use `logutils.Log` only. Logrus is banned via depguard" | Match |
| goimports with local prefix | "Local prefix `github.com/k8snetworkplumbingwg/ovs-cni`" | Match |
| Ginkgo v2 + Gomega dot-imports | "Dot-imports allowed for `ginkgo/v2`, `gomega`, `gomega/gstruct`" | Match |

**AGENTS.md has one rule not represented in the prompt:** "20+ linters enabled. Relaxed rules in `_test.go` files. Run `make lint` before submitting." The prompt explicitly says "Do NOT run builds, tests, or linters," so this is intentional, not drift.

This PR modifies only Go source and test files in `pkg/`. No new languages, test suites, or top-level areas were introduced.

_No drift detected._

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Code review | $0.4554 | 57s |
| Analysis | $0.6697 | 2m 34s |
| **Total** | **$1.1251** | **3m 31s** |

</details>

**Review by robot-helena — APPROVED** [review]
QA passed:  Review approved, 1 of 4 checks failed (all classified as flakes).

## Quality review

This PR delivers solid, well-crafted code that addresses the stated race conditions with proper testing and clean implementation. The InterfaceHasError refactoring properly leverages existing helpers, the Eventually() pattern correctly handles kernel interface availability, and all prior review feedback has been addressed. The code follows project conventions (DCO sign-offs, no prohibited logging, proper Ginkgo patterns) and demonstrates good engineering discipline with comprehensive test coverage including both unit and integration tests. The PR also includes a well-executed infrastructure migration from kubevirtci to kind (merged from PR #466) and mirror test timing fixes (issue #455), though these are not mentioned in the PR description—a minor documentation gap but not a code quality concern. Ready to merge.
✅ Approved — no concerns.

## Test results
❌ 1 of 4 checks failed.

| Check | Status |
|-------|--------|
| Build | ✅ passed |
| Lint | ✅ passed |
| Unit tests | ✅ passed |
| Functest | ❌ failed |

> ⚠️ 1 failure(s) classified as flake(s) and tracked separately:
> - Functest — [https://github.com/k8snetworkplumbingwg/ovs-cni/issues/461](https://github.com/k8snetworkplumbingwg/ovs-cni/issues/461)

**Failures**

<details>
<summary>Functest — 7 of 14 functional tests failed: ovs-mirror 1.0.0, ovs-cni 0.4.0 (2 tests), ovs-cni 0.3.0 (2 tests), ovs-cni 1.0.0 (2 tests), AfterSuite cleanup (exit 2)</summary>

`make cluster-down 2>/dev/null; make cluster-up && make cluster-sync && make E2E_TEST_ARGS="-ginkgo.v -test.v -test.timeout 20m -ginkgo.noColor" functest; rc=$?; make cluster-down; exit $rc`

```
=== RUN   TestPlugin
Running Suite: Plugin Suite - /tmp/qe-pr-464-wt/tests
=====================================================
Random Seed: 1775867155

Will run 14 of 14 specs

[...earlier tests passed...]

------------------------------
ovs-mirror 1.0.0 ovs traffic mirroring tests when an OVS bridge is configured on a node and both consumer and producer network attachment definitions are defined with a mirror configuration and 3 pods (2 producers and 1 consumer) are connected through it consumer pod should be able to monitor network traffic between producer pods
/tmp/qe-pr-464-wt/tests/mirror_test.go:91
  STEP: Adding ovs-bridge on the node @ 04/11/26 00:34:15.405
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl add-br br-test
  [FAILED] in [BeforeEach] - /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:15.552
  STEP: Removing ovs-bridge on the node @ 04/11/26 00:34:15.552
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl --if-exists del-br br-test
  [FAILED] in [AfterEach] - /tmp/qe-pr-464-wt/tests/node/node.go:61 @ 04/11/26 00:34:15.71
• [FAILED] [0.304 seconds]
ovs-mirror 1.0.0 ovs traffic mirroring tests when an OVS bridge is configured on a node [BeforeEach] and both consumer and producer network attachment definitions are defined with a mirror configuration and 3 pods (2 producers and 1 consumer) are connected through it consumer pod should be able to monitor network traffic between producer pods
  [BeforeEach] /tmp/qe-pr-464-wt/tests/mirror_test.go:37
  [It] /tmp/qe-pr-464-wt/tests/mirror_test.go:91

  [FAILED] Failed to run command on node. stdout: 
  Unexpected error:
      <*exec.ExitError | 0x2ef38a442000>: 
      exit status 127
      {
          ProcessState: {
              pid: 52309,
              status: 32512,
              rusage: {
                  Utime: {Sec: 0, Usec: 41978},
                  Stime: {Sec: 0, Usec: 31686},
                  Maxrss: 49132,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 6121,
                  Majflt: 8,
                  Nswap: 0,
                  Inblock: 3384,
                  Oublock: 1648,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 565,
                  Nivcsw: 28,
              },
          },
          Stderr: nil,
      }
  occurred
  In [BeforeEach] at: /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:15.552

------------------------------
ovs-cni 0.4.0 pod availability tests When ovs-cni is deployed on the cluster ovs-cni pod should be up and running
/tmp/qe-pr-464-wt/tests/ovs_test.go:39
  [FAILED] in [It] - /tmp/qe-pr-464-wt/tests/ovs_test.go:41 @ 04/11/26 00:34:15.711
• [FAILED] [0.001 seconds]
ovs-cni 0.4.0 pod availability tests When ovs-cni is deployed on the cluster [It] ovs-cni pod should be up and running
/tmp/qe-pr-464-wt/tests/ovs_test.go:39

  [FAILED] should have at least 1 ovs-cni pod deployed
  Expected
      <int>: 0
  to be >
      <int>: 0
  In [It] at: /tmp/qe-pr-464-wt/tests/ovs_test.go:41 @ 04/11/26 00:34:15.711

------------------------------
ovs-cni 0.4.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
/tmp/qe-pr-464-wt/tests/ovs_test.go:80
  STEP: Adding ovs-bridge on the node @ 04/11/26 00:34:15.711
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl add-br br-test
  [FAILED] in [BeforeEach] - /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:15.876
  STEP: Removing ovs-bridge on the node @ 04/11/26 00:34:15.876
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl --if-exists del-br br-test
  [FAILED] in [AfterEach] - /tmp/qe-pr-464-wt/tests/node/node.go:61 @ 04/11/26 00:34:16.035
• [FAILED] [0.325 seconds]
ovs-cni 0.4.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node [BeforeEach] and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
  [BeforeEach] /tmp/qe-pr-464-wt/tests/ovs_test.go:49
  [It] /tmp/qe-pr-464-wt/tests/ovs_test.go:80

  [FAILED] Failed to run command on node. stdout: 
  Unexpected error:
      <*exec.ExitError | 0x2ef38a252680>: 
      exit status 127
      {
          ProcessState: {
              pid: 52373,
              status: 32512,
              rusage: {
                  Utime: {Sec: 0, Usec: 56784},
                  Stime: {Sec: 0, Usec: 31867},
                  Maxrss: 47248,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 5826,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 1576,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 677,
                  Nivcsw: 108,
              },
          },
          Stderr: nil,
      }
  occurred
  In [BeforeEach] at: /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:15.876

------------------------------
ovs-cni 0.3.0 pod availability tests When ovs-cni is deployed on the cluster ovs-cni pod should be up and running
/tmp/qe-pr-464-wt/tests/ovs_test.go:39
  [FAILED] in [It] - /tmp/qe-pr-464-wt/tests/ovs_test.go:41 @ 04/11/26 00:34:16.037
• [FAILED] [0.001 seconds]
ovs-cni 0.3.0 pod availability tests When ovs-cni is deployed on the cluster [It] ovs-cni pod should be up and running
/tmp/qe-pr-464-wt/tests/ovs_test.go:39

  [FAILED] should have at least 1 ovs-cni pod deployed
  Expected
      <int>: 0
  to be >
      <int>: 0
  In [It] at: /tmp/qe-pr-464-wt/tests/ovs_test.go:41 @ 04/11/26 00:34:16.037

------------------------------
ovs-cni 0.3.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
/tmp/qe-pr-464-wt/tests/ovs_test.go:80
  STEP: Adding ovs-bridge on the node @ 04/11/26 00:34:16.037
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl add-br br-test
  [FAILED] in [BeforeEach] - /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:16.178
  STEP: Removing ovs-bridge on the node @ 04/11/26 00:34:16.178
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl --if-exists del-br br-test
  [FAILED] in [AfterEach] - /tmp/qe-pr-464-wt/tests/node/node.go:61 @ 04/11/26 00:34:16.32
• [FAILED] [0.283 seconds]
ovs-cni 0.3.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node [BeforeEach] and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
  [BeforeEach] /tmp/qe-pr-464-wt/tests/ovs_test.go:49
  [It] /tmp/qe-pr-464-wt/tests/ovs_test.go:80

  [FAILED] Failed to run command on node. stdout: 
  Unexpected error:
      <*exec.ExitError | 0x2ef38a2526a0>: 
      exit status 127
      {
          ProcessState: {
              pid: 52434,
              status: 32512,
              rusage: {
                  Utime: {Sec: 0, Usec: 52018},
                  Stime: {Sec: 0, Usec: 29874},
                  Maxrss: 48292,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 6003,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 1576,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 588,
                  Nivcsw: 32,
              },
          },
          Stderr: nil,
      }
  occurred
  In [BeforeEach] at: /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:16.178

------------------------------
ovs-cni 1.0.0 pod availability tests When ovs-cni is deployed on the cluster ovs-cni pod should be up and running
/tmp/qe-pr-464-wt/tests/ovs_test.go:39
  [FAILED] in [It] - /tmp/qe-pr-464-wt/tests/ovs_test.go:41 @ 04/11/26 00:34:16.321
• [FAILED] [0.001 seconds]
ovs-cni 1.0.0 pod availability tests When ovs-cni is deployed on the cluster [It] ovs-cni pod should be up and running
/tmp/qe-pr-464-wt/tests/ovs_test.go:39

  [FAILED] should have at least 1 ovs-cni pod deployed
  Expected
      <int>: 0
  to be >
      <int>: 0
  In [It] at: /tmp/qe-pr-464-wt/tests/ovs_test.go:41 @ 04/11/26 00:34:16.321

------------------------------
ovs-cni 1.0.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
/tmp/qe-pr-464-wt/tests/ovs_test.go:80
  STEP: Adding ovs-bridge on the node @ 04/11/26 00:34:16.321
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl add-br br-test
  [FAILED] in [BeforeEach] - /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:16.438
  STEP: Removing ovs-bridge on the node @ 04/11/26 00:34:16.438
  ./cluster/exec.sh ovs-cni-worker -- ovs-vsctl --if-exists del-br br-test
  [FAILED] in [AfterEach] - /tmp/qe-pr-464-wt/tests/node/node.go:61 @ 04/11/26 00:34:16.584
• [FAILED] [0.263 seconds]
ovs-cni 1.0.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node [BeforeEach] and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
  [BeforeEach] /tmp/qe-pr-464-wt/tests/ovs_test.go:49
  [It] /tmp/qe-pr-464-wt/tests/ovs_test.go:80

  [FAILED] Failed to run command on node. stdout: 
  Unexpected error:
      <*exec.ExitError | 0x2ef38a253080>: 
      exit status 127
      {
          ProcessState: {
              pid: 52500,
              status: 32512,
              rusage: {
                  Utime: {Sec: 0, Usec: 48447},
                  Stime: {Sec: 0, Usec: 21145},
                  Maxrss: 47964,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 5858,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 1672,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 729,
                  Nivcsw: 31,
              },
          },
          Stderr: nil,
      }
  occurred
  In [BeforeEach] at: /tmp/qe-pr-464-wt/tests/node/node.go:68 @ 04/11/26 00:34:16.438

------------------------------
[AfterSuite] 
/tmp/qe-pr-464-wt/tests/tests_suite_test.go:54
  STEP: Waiting for namespace test-namespace to be removed, this can take a while ... @ 04/11/26 00:34:16.584
  [FAILED] in [AfterSuite] - /tmp/qe-pr-464-wt/tests/cluster/cluster.go:82 @ 04/11/26 00:34:16.585
[AfterSuite] [FAILED] [0.001 seconds]
[AfterSuite] 
/tmp/qe-pr-464-wt/tests/tests_suite_test.go:54

  [FAILED] Should succeed deleting namespace if exists
  Expected
      <*url.Error | 0x2ef38a9d73e0>: 
      Delete "https://127.0.0.1:39667/api/v1/namespaces/test-namespace": dial tcp 127.0.0.1:39667: connect: connection refused
      {
          Op: "Delete",
          URL: "https://127.0.0.1:39667/api/v1/namespaces/test-namespace",
          Err: <*net.OpError | 0x2ef38a7a8b90>{
              Op: "dial",
              Net: "tcp",
              Source: nil,
              Addr: <*net.TCPAddr | 0x2ef38a9d7380>{
                  IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
                  Port: 39667,
                  Zone: "",
              },
              Err: <*os.SyscallError | 0x2ef38a4428c0>{
                  Syscall: "connect",
                  Err: <syscall.Errno>0x6f,
              },
          },
      }
  To satisfy at least one of these matchers: [%!s(*matchers.BeNilMatcher=&{}) %!s(*matchers.WithTransformMatcher=&{0xbf1020 0x2ef38a44fb60 0x1956380 false})]
  In [AfterSuite] at: /tmp/qe-pr-464-wt/tests/cluster/cluster.go:82 @ 04/11/26 00:34:16.585
------------------------------

Summarizing 8 Failures:
  [FAIL] ovs-mirror 1.0.0 ovs traffic mirroring tests when an OVS bridge is configured on a node [BeforeEach] and both consumer and producer network attachment definitions are defined with a mirror configuration and 3 pods (2 producers and 1 consumer) are connected through it consumer pod should be able to monitor network traffic between producer pods
  /tmp/qe-pr-464-wt/tests/node/node.go:68
  [FAIL] ovs-cni 0.4.0 pod availability tests When ovs-cni is deployed on the cluster [It] ovs-cni pod should be up and running
  /tmp/qe-pr-464-wt/tests/ovs_test.go:41
  [FAIL] ovs-cni 0.4.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node [BeforeEach] and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
  /tmp/qe-pr-464-wt/tests/node/node.go:68
  [FAIL] ovs-cni 0.3.0 pod availability tests When ovs-cni is deployed on the cluster [It] ovs-cni pod should be up and running
  /tmp/qe-pr-464-wt/tests/ovs_test.go:41
  [FAIL] ovs-cni 0.3.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node [BeforeEach] and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
  /tmp/qe-pr-464-wt/tests/node/node.go:68
  [FAIL] ovs-cni 1.0.0 pod availability tests When ovs-cni is deployed on the cluster [It] ovs-cni pod should be up and running
  /tmp/qe-pr-464-wt/tests/ovs_test.go:41
  [FAIL] ovs-cni 1.0.0 pod ovs-bridge connectivity tests when an OVS bridge is configured on a node [BeforeEach] and a network attachment definition is defined and two pods are connected through it they should be able to communicate over the network
  /tmp/qe-pr-464-wt/tests/node/node.go:68
  [FAIL] [AfterSuite] 
  /tmp/qe-pr-464-wt/tests/cluster/cluster.go:82

Ran 14 of 14 Specs in 501.310 seconds
FAIL! -- 7 Passed | 7 Failed | 0 Pending | 0 Skipped
--- FAIL: TestPlugin (501.31s)
FAIL
FAIL	github.com/k8snetworkplumbingwg/ovs-cni/tests	501.332s
FAIL
make: *** [Makefile:84: functest] Error 1
```
_(output trimmed: middle elided)_
</details>

## Analysis

<details>
<summary>Quality review</summary>

**Stats**

- Wall time: 4m 52s
- Tokens: 216 in · 12.6k out · 783.8k cache-read · 71.8k cache-create
- Run dir: `/tmp/qe-runs/2026-04-11T00-17-49-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 39 | 2m 16s |
| Read | 4 | 1m 07s |
| Write | 1 | 1m 01s |
| Grep | 2 | 13s |

**Analysis**

**Tool call wall time distribution:**
The review stage executed 46 tool calls, all sequentially (zero parallel batches). The longest operations were:
- 30 sequential `git diff` commands (calls 3-32), taking an estimated 2-3 minutes of wall time
- Several grep/read operations for verification (calls 34-45)

**Inefficiencies identified:**

1. **Unnecessary diffs (23 files)**: The PR changed only 7 files, but the review ran `git diff origin/main...HEAD -- <path>` on 30 files. This happened because the review diffed every file returned by some earlier command, including files from the broader repository that weren't part of this PR (cluster scripts, docs, hack scripts, etc.). Wall time wasted: ~2 minutes.

2. **Sequential instead of parallel diffs**: The review-prompt.txt explicitly states at line 166: "Issue ALL per-file diffs in a SINGLE parallel tool-call turn." The review ignored this and ran 30 git diff commands in 30 sequential turns. Even for just the 7 changed files, parallel execution would have saved ~1.5 minutes.

3. **No batching at all**: Zero tool calls were batched. Every Bash/Read/Grep operation ran in its own turn, forcing full prompt re-processing each time.

**Concrete suggestions:**
1. Before running per-file diffs, validate that each file path appears in the `git diff --name-only` output. Skip files that weren't changed. **Estimated savings: 2 minutes.**
2. Enforce parallel batch execution: All per-file git diffs for the 7 changed files should be sent in one message with 7 Bash tool calls. **Estimated savings: 1.5 minutes.**

Total estimated savings: **3.5 minutes** of wall time.

</details>

<details>
<summary>Test run</summary>

**Stats**

- Wall time: 15m 07s
- Tokens: 149 in · 9.6k out · 357.1k cache-read · 39.7k cache-create
- Run dir: `/tmp/qe-runs/2026-04-11T00-17-49-pr464`

**Tool calls**

| Tool | Calls | Cumulative time |
|------|-------|-----------------|
| Bash | 11 | 13m 09s |
| Write | 1 | 1m 26s |
| Grep | 1 | 13s |
| Read | 1 | 4s |

</details>

<details>
<summary>Script drift</summary>

1. **Missing test target**: The Makefile contains a `docker-test` target (line 77) that runs `hack/test-dockerized.sh`. This is not executed by the QE test prompt. The QE prompt runs `make build`, `make lint`, `make test`, and `make functest`, but skips `docker-test`. Investigation of `test-dockerized.sh` shows it's a containerized test runner (likely redundant with the regular `make test`), but the prompt should document why it's excluded or include it.
   - **Change needed in `agentic/agents/agentic/quality/`**: Add `docker-test` to the test pipeline, or add a comment in the test prompt template explaining why `docker-test` is deliberately excluded (if it's redundant with `make test`).

2. **Test parallelization not enforced**: The QE test prompt explicitly says (line 54): "You MUST launch ALL THREE of them together by sending THREE Bash tool calls in a SINGLE message." But the test stage ran build, lint, and test sequentially in separate turns. This is a prompt compliance issue, not drift, but the orchestrator should validate that independent checks are batched.
   - **Change needed in `agentic/agents/agentic/quality/`**: Add validation that build/lint/test commands appear in the same tool-use batch, or improve the prompt phrasing to make batching non-optional.

3. **Review parallelization not enforced**: Similar to above, the review prompt says diffs must be parallel, but they ran sequentially.
   - **Change needed in `agentic/agents/agentic/quality/`**: Add post-run validation that per-file diffs were batched, or refactor the review prompt to use a single `git diff` with multiple file paths in one command instead of relying on Claude to batch correctly.

</details>

<details>
<summary>Cost</summary>

| Stage | Cost | Wall time |
|-------|-----:|----------:|
| Quality review | $0.6940 | 4m 52s |
| Test run | $0.3997 | 15m 07s |
| Analysis | $0.4500 | 3m 07s |
| **Total** | **$1.5438** | **23m 06s** |

</details>

**Review by phoracek — APPROVED** [review]
/lgtm
/approve
